version: '3'

networks:
  proxy:
    external: true
  mongo:
    internal: true

services:
  dnd:
    image: maael/dnd.mael.tech:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/dnd
      DEBUG:
    labels:
      - traefik.backend=dnd
      - traefik.frontend.rule=Host:dnd.mael.tech
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - proxy
      - mongo

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./data/db:/data/db
      - ./data/log:/data/log
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    labels:
      - traefik.backend=dnd-db
      - traefik.frontend.rule=Host:dnd-db.mael.tech
      - traefik.docker.network=proxy
      - traefik.port=8082
    networks:
      - proxy
      - mongo
